services:
    _defaults:
        public: true

    coreshop.payment.payment_provider_resolver:
        alias: CoreShop\Component\Payment\Resolver\PaymentProviderResolver
        deprecated: { package: "coreshop/payment-bundle", version: "3.0", message: 'The "%alias_id%" service alias is deprecated since CoreShop 3.0 and will be removed with 3.1, use CoreShop\Component\Payment\Resolver\PaymentProviderResolver instead' }

