services:
    coreshop.pimcore.document.tag.payment_provider:
        class: CoreShop\Component\Resource\Pimcore\ResourceDocumentTagFactory
        arguments:
            - 'CoreShop\Bundle\ResourceBundle\CoreExtension\Document\Select'
            - 'coreshop.repository.payment_provider'
            - 'name'
        tags:
            - { name: coreshop.pimcore.document.tag, type: coreshop_payment_provider }