CoreShop\Component\Payment\Model\Payment:
  type: mappedSuperclass
  table: coreshop_payment
  fields:
    id:
      type: integer
      column: id
      id: true
      generator:
        strategy: AUTO
    state:
      column: state
      type: string
    orderId:
      column: orderId
      type: integer
    datePayment:
      column: datePayment
      type: datetime
  manyToOne:
    paymentProvider:
      targetEntity: CoreShop\Component\Payment\Model\PaymentProviderInterface
      joinColumn:
        name: payment_provider_id
        referencedColumnName: id
        nullable: true
    currency:
      targetEntity: CoreShop\Component\Currency\Model\CurrencyInterface
      joinColumn:
        name: currency_id
        referencedColumnName: id
        nullable: false