framework:
  workflows:
    coreshop_payment:
      type: 'state_machine'
      marking_store:
        service: coreshop.state_machine.marking_store.payment_orm_marketing_store
      supports: CoreShop\Component\Payment\Model\Payment
      places:
          - new
          - processing
          - completed
          - failed
          - cancelled
          - refunded
      transitions:
        process:
          from: [new]
          to: processing
        complete:
          from: [new, processing]
          to: completed
        fail:
          from: [new, processing]
          to: failed
        cancel:
          from: [new, processing]
          to: cancelled
        refund:
          from: [completed]
          to: refunded